### ISSUE TITLE
sed: can't read /app/kafka-mqtt-connector/application.properties

### ISSUE THREAD

**Issue by fabiankaimer** [ipa-digitools/simple-kafka-mqtt-connector#5]
First of all, thank you for the great tool :)

I had the connector seamlessly running as a docker container during the last days. I pulled it directly from DockerHub and it worked just fine. To apply some changes to adapt the tool to my needs (I haven't changed anything yet), I cloned the repo, built it with maven and tried to started it locally with docker-compose. But now, I get the error `sed: can't read /app/kafka-mqtt-connector/application.properties` that originates from setConfiguration.sh file. I'm running docker on Windows 10.

Do you have any idea where this might be coming from? Thanks in advance for your help.

**Comment by AGRG-IPA-070** [comment]
You are welcome :)
Glad to hear that.

The problem is that windows is changing the line endigs to /r/n (see https://stackoverflow.com/questions/16239551/eol-conversion-in-notepad#answer-31601923).

I use notepad++ to replace \r\n with \n 
(view line endings by clicking: view > show symbol > show end of line)
(press ctrl+f > open the replace tab > make sure to tick 'search mode' 'extended' > replace '\r\n' with '\n' > safe > run the docker build again)

To be honest, I've built it on ubuntu so I don't guarantee this will work but it should.

**Comment by fabiankaimer** [comment]
Wow great, it worked! Thanks for the quick reply and the help! I'm closing this issue.
